name: "Assign to me"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["Azure Subscription"]'
          assignees: '["tescales"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
